application: splunk-sizing
version: subscription
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "1m"

handlers:
- url: /news/.*
  script: news.app

- url: /$
  static_files: index.html
  upload: index.html$

- url: /(.+\.(gif|png|jpg|ico|css|js))$
  static_files: \1
  upload: .+\.(gif|png|jpg|ico|css|js)$

- url: /_ah/mail/.+
  script: news.app
  login: admin

libraries:
- name: webapp2
  version: latest
